name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file net3.1_java/Dockerfile --tag dotnet_3.1_java:$(date +%s) --tag dotnet_3.1_java:latest
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: simonmau/dotnet-java/dotnet_3.1_java
          tag_with_ref: true
